// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD0Za1xNz51ZOJjjW3CufiHMacT3aW60M',
    appId: '1:742913405292:web:ba92d04f9ec4f48b5c4349',
    messagingSenderId: '742913405292',
    projectId: 'bobook-36d20',
    authDomain: 'bobook-36d20.firebaseapp.com',
    databaseURL: 'https://bobook-36d20-default-rtdb.firebaseio.com',
    storageBucket: 'bobook-36d20.appspot.com',
    measurementId: 'G-K900HV0HW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOFFZ-sLK30hXdrO4ieEfO31tRai29z20',
    appId: '1:742913405292:android:7b8b126af04194275c4349',
    messagingSenderId: '742913405292',
    projectId: 'bobook-36d20',
    databaseURL: 'https://bobook-36d20-default-rtdb.firebaseio.com',
    storageBucket: 'bobook-36d20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ6gokC_B0JQ-CRww2GzlPeRaM1sWwB2I',
    appId: '1:742913405292:ios:ff1b923a7ec3424a5c4349',
    messagingSenderId: '742913405292',
    projectId: 'bobook-36d20',
    databaseURL: 'https://bobook-36d20-default-rtdb.firebaseio.com',
    storageBucket: 'bobook-36d20.appspot.com',
    iosBundleId: 'com.example.bobook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ6gokC_B0JQ-CRww2GzlPeRaM1sWwB2I',
    appId: '1:742913405292:ios:ff1b923a7ec3424a5c4349',
    messagingSenderId: '742913405292',
    projectId: 'bobook-36d20',
    databaseURL: 'https://bobook-36d20-default-rtdb.firebaseio.com',
    storageBucket: 'bobook-36d20.appspot.com',
    iosBundleId: 'com.example.bobook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD0Za1xNz51ZOJjjW3CufiHMacT3aW60M',
    appId: '1:742913405292:web:41e09f3102e8a53c5c4349',
    messagingSenderId: '742913405292',
    projectId: 'bobook-36d20',
    authDomain: 'bobook-36d20.firebaseapp.com',
    databaseURL: 'https://bobook-36d20-default-rtdb.firebaseio.com',
    storageBucket: 'bobook-36d20.appspot.com',
    measurementId: 'G-X7D0HSETZK',
  );
}
